### PR TITLE
Added transient config option

### PR DESCRIPTION
**Pull request by Karol-Waliszewski**

### CODE REVIEW

**Comment by Karol-Waliszewski** [comment]
@vinpac, I'll be really glad if you check out my request 👍

**Comment by vinpac** [comment]
Interesting. Could you please add a docs page explaining this functionality, please?

Thanks for the PR.

Do a version a bump too on this PR, so when it's merged it gets published

**Comment by Karol-Waliszewski** [comment]
@vinpac, Docs section explaining `transient` has been added. I also bumped version to 0.2.1 👍

**Comment by vinpac** [comment]
Hey @Karol-Waliszewski, I really wanna thank you for this contribution. It's something that I also need on a personal project. 

Thanks!

**Pull request merged**
